<?php

namespace app\widgets\HistoryList\helpers;

use app\widgets\HistoryList\strategies\HistoryListStrategyFactory;
use app\models\History;

class HistoryListHelper
{
    /**
     * This method takes a History model instance and returns the appropriate body text
     * based on the event type using the Strategy pattern.
     *
     * @param History $model The History model instance for which the body text needs to be generated.
     * @return string The body text generated by the corresponding strategy.
     */
    public static function getBodyByModel(History $model)
    {
        // Get the appropriate strategy instance based on the event type from the factory.
        $strategy = HistoryListStrategyFactory::getStrategy($model->event);

        // Call the getBody method of the strategy instance to generate the body text.
        return $strategy->getBody($model);
    }
}